backend:
  name: git-gateway
  branch: main  # GitHub ana dal adı (az önce doğruladık, main kullanıyorsun)

media_folder: "images/uploads"   # Yüklenen resimler bu klasörde saklanacak
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Sayfalar"
    files:
      - label: "Ana Sayfa"
        name: "home"
        file: "index.html"
        fields:
          - {label: "Başlık", name: "title", widget: "string"}
          - {label: "Açıklama", name: "description", widget: "text"}
          - {label: "Ana Resim", name: "image", widget: "image"}
